### ISSUE TITLE
Overflow on mobile device

### ISSUE THREAD

**Issue by peterpeterparker** [sdras/hero-generator#1]
### Description

I tested your nice tool on my mobile device (OnePlus 6 / Android 10) and noticed a small overflow-x.

Didn't debug it but it looks like related to the input fields.

It wasn't a problem at all but since I noticed it, I thought about reporting it quickly 😉

### Screenshot

![Screenshot_20200427-171927](https://user-images.githubusercontent.com/16886711/80389411-55e3d080-88ab-11ea-9001-b6bb3da4e29a.jpg)

**Comment by sdras** [comment]
Dang, I did a few things to try to preemptively keep this from happening, but don't have an android. Thanks for letting me know! I'll fix it up. Open to PRs too.
