### ISSUE TITLE
Color picker window overlay visible among tabs in chrome

### ISSUE THREAD

**Issue by pndirpaya** [sdras/hero-generator#9]
Hi Sarah, 

Pretty Awesome Product you've got here. 

i don't know if this is a big deal, but i noticed that the color picker for the buttons remains open and overlays within other tabs when the window isn't explicitly closed. 
It still stays open when the hero-generator browser tab is closed and also when a new tab is open. 

i checked the behaviour on the safari browser and it works ideally by closing the overlay window when the hero-generator tab is closed or a new tab is opened. 

so i believe it is a bug worth looking at on chrome. 

**Screenshot**
![Screenshot 2020-05-01 at 02 33 22](https://user-images.githubusercontent.com/21107129/80774451-fd376080-8b54-11ea-8186-4edb4302d9d7.png)

great job on this.

**Comment by sdras** [comment]
This is unfortunately the behavior of the native color picker, not the project. You can file a bug with w3c I think. Thanks!
